project:
  type: website
  output-dir: docs

website:
  title: "Métodos Numéricos" 
  # O Quarto usará o 'index.qmd' como página inicial.
  # Nenhum bloco 'navbar' ou 'sidebar' está presente.

  
format:
  html:
    theme: default
    lang: pt-BR
    scss: TemaRTx.scss
    
  revealjs:
    theme: default
    scss: TemaRTx.scss
    transition: slide
    slide-number: true
    footer: "Métodos Numéricos UFPA - Prof. Dr. Raphael Teixeira"
    width: 1600      # Largura
    height: 900       # Altura
    code-theme: monokai
    code-font-size: 2.0em
    code-line-numbers: true
    