project:
  type: website
  output-dir: docs

website:
  # O website é definido, mas sem barras de navegação (navbar ou sidebar)
  title: "Métodos Numéricos UFPA" 
  # NOTA: O Quarto usará o 'index.qmd' como página inicial.
  # Nenhum bloco 'navbar' ou 'sidebar' está presente.
  
format:
  html:
    theme: default
    lang: pt-BR
    scss: TemaRTx.scss
    
  revealjs:
    theme: default
    scss: TemaRTx.scss