project:
  type: website
  output-dir: docs

website:
  # O website é definido, mas sem barras de navegação (navbar ou sidebar)
  title: "Métodos Numéricos UFPA" 
  # NOTA: O Quarto usará o 'index.qmd' como página inicial.
  # Nenhum bloco 'navbar' ou 'sidebar' está presente.
  
format:
  # Configuração para o website (index.qmd)
  html:
    # APLICAÇÃO DO TEMA SCSS: Processa as variáveis definidas em TemaRTx.scss
    theme: TemaRTx.scss 
    lang: pt-BR
    
  # Configuração para os Slides (AjusteCurvas.qmd e RaizesNaoLineares.qmd)
  revealjs:
    # APLICAÇÃO DO TEMA SCSS: Garante que os estilos do TemaRTx.scss sejam usados nos slides
    theme: TemaRTx.scss